Fix escaping of extension schemas
The schema name got "doubly escaped" by mistake, causing failures
if the extension is installed in a schema with non-standard name.

This caused errors like
  ERROR:  schema """""with spaceq""""" does not exist

Reported by "Cr4zyCoder1337" in cybertec-postgresql/db_migrator#4.