Add missing privilege required in regression test
This fixes

ERROR:  error executing statement: OCIStmtExecute failed to execute query
DETAIL:  ORA-01031: insufficient privileges
CONTEXT:  SQL statement "SELECT public.oracle_execute ('oracle', 'DROP TRIGGER "TESTSCHEMA2"."__Log_TAB3_TRIG"')"
PL/pgSQL function public.oracle_replication_finish(name,name) line 35 at EXECUTE

during oracle_replication_finish run